import turtle
t=turtle.Turtle()
t.shape('turtle')
s=turtle.textinput("","이름을 입력하세요:")
t.write("안녕하세요?"+s+"씨, 다현 인사드립니다.")
wn=turtle.Screen()
wn.bgcolor("black")
t.begin_fill()
t.color("red")
s=turtle.textinput("","이름을 입력하세요:")
t.write("안녕하세요?"+s+"씨, 다현 인사드립니다.")
t.left(45)
t.forward(200)
t.circle(73,211.37)
t.left(180)
t.circle(73,211.37)
t.forward(200)
t.end_fill()
